-- Verificar colunas da tabela premios relacionadas a pagamento
SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_COMMENT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = DATABASE()
AND TABLE_NAME = 'premios' 
AND COLUMN_NAME LIKE '%pagamento%'
ORDER BY ORDINAL_POSITION;
